### ISSUE TITLE
do not have the irt_sheet.tsv

### ISSUE THREAD

**Issue by lzy604** [nf-core/diaproteomics#148] opened 2022-07-07 14:50 UTC
Dear authors,

Thanks for developing this tools for DIA_MS data analysis. I want to know if I can analyze the DIA without irt_sheet.tsv. Also can I use my own fasta to do the alignment?

**Comment by Leon-Bichmann** [comment] 2022-07-08 09:16
Hi,
Thanks for checking out this workflow, its been a while that I was working on this but let me try to help here - were you using any kind of irts in your experiment? or do you have a library of cirts that you could use that are typically found in proteomics samples? Just from a fasta its not possible but there is an alternative option to generate pseudo_irts using the flag "--generate_pseudo_irts". It uses very confident Ids from your library across the RT range in order to do the alignment.

**Comment by lzy604** [comment] 2022-07-08 14:09
Thanks for your reply. There are no any kind of arts in the experiment. It is said that we can use the housekeeping gene to as this.Also the Diann use deep learning method to generate one library for this. Is this like generate pseudo_irts?  I just wonder if we do not give the fasta, how to do the alignment. How does the software know the species of the samples?

**Comment by Leon-Bichmann** [comment] 2022-07-08 14:46
No problem, DIA-NN is an entirely different approach that can do library-free search. This workflow here uses the "classical" library-based approach. You could give the "generate_pseudo_irts" option a try for your samples, but maybe youre better off using DIA-NN or other workflows. In any case, as this is not a bug but rather a special application I would prefer to close the issue again.

**Comment by lzy604** [comment] 2022-07-08 19:54
Thanks for your reply. I will try 'generate_pseudo_irt'.  I still do not understand the alignment.I just wonder if we do not give the fasta, how to do the alignment. How does the software know the species of the samples?

**Comment by Leon-Bichmann** [comment] 2022-07-09 07:29
There is no need to know the organism. Please check the paper again - the alignment should be explained in there.

**Closed as completed by Leon-Bichmann** 2022-07-09 07:29 UTC
Labels: bug
